// Code generated by protoc-gen-go. DO NOT EDIT.
// source: otaru.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	otaru.proto

It has these top-level messages:
	ListDirRequest
	ListDirResponse
	GetBlobstoreConfigRequest
	GetBlobstoreConfigResponse
	ReduceCacheRequest
	ReduceCacheResponse
	GetEntriesRequest
	GetEntriesResponse
	GetCategoriesRequest
	LoggerCategory
	GetCategoriesResponse
	SetCategoryRequest
	SetCategoryResponse
	GetSystemInfoRequest
	SystemInfoResponse
	GetVersionRequest
	VersionResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ListDirRequest struct {
	Path string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
}

func (m *ListDirRequest) Reset()                    { *m = ListDirRequest{} }
func (m *ListDirRequest) String() string            { return proto.CompactTextString(m) }
func (*ListDirRequest) ProtoMessage()               {}
func (*ListDirRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ListDirRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type ListDirResponse struct {
	Entry []*ListDirResponse_Entry `protobuf:"bytes,1,rep,name=entry" json:"entry,omitempty"`
}

func (m *ListDirResponse) Reset()                    { *m = ListDirResponse{} }
func (m *ListDirResponse) String() string            { return proto.CompactTextString(m) }
func (*ListDirResponse) ProtoMessage()               {}
func (*ListDirResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ListDirResponse) GetEntry() []*ListDirResponse_Entry {
	if m != nil {
		return m.Entry
	}
	return nil
}

type ListDirResponse_Entry struct {
	Id           uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name         string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Type         string `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	Size         int64  `protobuf:"varint,4,opt,name=size" json:"size,omitempty"`
	Uid          uint32 `protobuf:"varint,5,opt,name=uid" json:"uid,omitempty"`
	Gid          uint32 `protobuf:"varint,6,opt,name=gid" json:"gid,omitempty"`
	PermMode     uint32 `protobuf:"varint,7,opt,name=perm_mode,json=permMode" json:"perm_mode,omitempty"`
	ModifiedTime int64  `protobuf:"varint,8,opt,name=modified_time,json=modifiedTime" json:"modified_time,omitempty"`
}

func (m *ListDirResponse_Entry) Reset()                    { *m = ListDirResponse_Entry{} }
func (m *ListDirResponse_Entry) String() string            { return proto.CompactTextString(m) }
func (*ListDirResponse_Entry) ProtoMessage()               {}
func (*ListDirResponse_Entry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

func (m *ListDirResponse_Entry) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ListDirResponse_Entry) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListDirResponse_Entry) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ListDirResponse_Entry) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ListDirResponse_Entry) GetUid() uint32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *ListDirResponse_Entry) GetGid() uint32 {
	if m != nil {
		return m.Gid
	}
	return 0
}

func (m *ListDirResponse_Entry) GetPermMode() uint32 {
	if m != nil {
		return m.PermMode
	}
	return 0
}

func (m *ListDirResponse_Entry) GetModifiedTime() int64 {
	if m != nil {
		return m.ModifiedTime
	}
	return 0
}

type GetBlobstoreConfigRequest struct {
}

func (m *GetBlobstoreConfigRequest) Reset()                    { *m = GetBlobstoreConfigRequest{} }
func (m *GetBlobstoreConfigRequest) String() string            { return proto.CompactTextString(m) }
func (*GetBlobstoreConfigRequest) ProtoMessage()               {}
func (*GetBlobstoreConfigRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type GetBlobstoreConfigResponse struct {
	BackendImplName string `protobuf:"bytes,1,opt,name=backend_impl_name,json=backendImplName" json:"backend_impl_name,omitempty"`
	BackendFlags    string `protobuf:"bytes,2,opt,name=backend_flags,json=backendFlags" json:"backend_flags,omitempty"`
	CacheImplName   string `protobuf:"bytes,3,opt,name=cache_impl_name,json=cacheImplName" json:"cache_impl_name,omitempty"`
	CacheFlags      string `protobuf:"bytes,4,opt,name=cache_flags,json=cacheFlags" json:"cache_flags,omitempty"`
}

func (m *GetBlobstoreConfigResponse) Reset()                    { *m = GetBlobstoreConfigResponse{} }
func (m *GetBlobstoreConfigResponse) String() string            { return proto.CompactTextString(m) }
func (*GetBlobstoreConfigResponse) ProtoMessage()               {}
func (*GetBlobstoreConfigResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetBlobstoreConfigResponse) GetBackendImplName() string {
	if m != nil {
		return m.BackendImplName
	}
	return ""
}

func (m *GetBlobstoreConfigResponse) GetBackendFlags() string {
	if m != nil {
		return m.BackendFlags
	}
	return ""
}

func (m *GetBlobstoreConfigResponse) GetCacheImplName() string {
	if m != nil {
		return m.CacheImplName
	}
	return ""
}

func (m *GetBlobstoreConfigResponse) GetCacheFlags() string {
	if m != nil {
		return m.CacheFlags
	}
	return ""
}

type ReduceCacheRequest struct {
	DryRun      bool   `protobuf:"varint,1,opt,name=dry_run,json=dryRun" json:"dry_run,omitempty"`
	DesiredSize string `protobuf:"bytes,2,opt,name=desired_size,json=desiredSize" json:"desired_size,omitempty"`
}

func (m *ReduceCacheRequest) Reset()                    { *m = ReduceCacheRequest{} }
func (m *ReduceCacheRequest) String() string            { return proto.CompactTextString(m) }
func (*ReduceCacheRequest) ProtoMessage()               {}
func (*ReduceCacheRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ReduceCacheRequest) GetDryRun() bool {
	if m != nil {
		return m.DryRun
	}
	return false
}

func (m *ReduceCacheRequest) GetDesiredSize() string {
	if m != nil {
		return m.DesiredSize
	}
	return ""
}

type ReduceCacheResponse struct {
	Success      bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage" json:"error_message,omitempty"`
}

func (m *ReduceCacheResponse) Reset()                    { *m = ReduceCacheResponse{} }
func (m *ReduceCacheResponse) String() string            { return proto.CompactTextString(m) }
func (*ReduceCacheResponse) ProtoMessage()               {}
func (*ReduceCacheResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ReduceCacheResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ReduceCacheResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type GetEntriesRequest struct {
}

func (m *GetEntriesRequest) Reset()                    { *m = GetEntriesRequest{} }
func (m *GetEntriesRequest) String() string            { return proto.CompactTextString(m) }
func (*GetEntriesRequest) ProtoMessage()               {}
func (*GetEntriesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type GetEntriesResponse struct {
	Entry []*GetEntriesResponse_Entry `protobuf:"bytes,1,rep,name=entry" json:"entry,omitempty"`
}

func (m *GetEntriesResponse) Reset()                    { *m = GetEntriesResponse{} }
func (m *GetEntriesResponse) String() string            { return proto.CompactTextString(m) }
func (*GetEntriesResponse) ProtoMessage()               {}
func (*GetEntriesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *GetEntriesResponse) GetEntry() []*GetEntriesResponse_Entry {
	if m != nil {
		return m.Entry
	}
	return nil
}

type GetEntriesResponse_Entry struct {
	BlobPath              string `protobuf:"bytes,1,opt,name=blob_path,json=blobPath" json:"blob_path,omitempty"`
	State                 string `protobuf:"bytes,2,opt,name=state" json:"state,omitempty"`
	BlobLen               int64  `protobuf:"varint,3,opt,name=blob_len,json=blobLen" json:"blob_len,omitempty"`
	ValidLen              int64  `protobuf:"varint,4,opt,name=valid_len,json=validLen" json:"valid_len,omitempty"`
	SyncCount             int64  `protobuf:"varint,5,opt,name=sync_count,json=syncCount" json:"sync_count,omitempty"`
	LastUsed              int64  `protobuf:"varint,6,opt,name=last_used,json=lastUsed" json:"last_used,omitempty"`
	LastWrite             int64  `protobuf:"varint,7,opt,name=last_write,json=lastWrite" json:"last_write,omitempty"`
	LastSync              int64  `protobuf:"varint,8,opt,name=last_sync,json=lastSync" json:"last_sync,omitempty"`
	NumberOfWriterHandles int64  `protobuf:"varint,9,opt,name=number_of_writer_handles,json=numberOfWriterHandles" json:"number_of_writer_handles,omitempty"`
	NumberOfHandles       int64  `protobuf:"varint,10,opt,name=number_of_handles,json=numberOfHandles" json:"number_of_handles,omitempty"`
}

func (m *GetEntriesResponse_Entry) Reset()                    { *m = GetEntriesResponse_Entry{} }
func (m *GetEntriesResponse_Entry) String() string            { return proto.CompactTextString(m) }
func (*GetEntriesResponse_Entry) ProtoMessage()               {}
func (*GetEntriesResponse_Entry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7, 0} }

func (m *GetEntriesResponse_Entry) GetBlobPath() string {
	if m != nil {
		return m.BlobPath
	}
	return ""
}

func (m *GetEntriesResponse_Entry) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *GetEntriesResponse_Entry) GetBlobLen() int64 {
	if m != nil {
		return m.BlobLen
	}
	return 0
}

func (m *GetEntriesResponse_Entry) GetValidLen() int64 {
	if m != nil {
		return m.ValidLen
	}
	return 0
}

func (m *GetEntriesResponse_Entry) GetSyncCount() int64 {
	if m != nil {
		return m.SyncCount
	}
	return 0
}

func (m *GetEntriesResponse_Entry) GetLastUsed() int64 {
	if m != nil {
		return m.LastUsed
	}
	return 0
}

func (m *GetEntriesResponse_Entry) GetLastWrite() int64 {
	if m != nil {
		return m.LastWrite
	}
	return 0
}

func (m *GetEntriesResponse_Entry) GetLastSync() int64 {
	if m != nil {
		return m.LastSync
	}
	return 0
}

func (m *GetEntriesResponse_Entry) GetNumberOfWriterHandles() int64 {
	if m != nil {
		return m.NumberOfWriterHandles
	}
	return 0
}

func (m *GetEntriesResponse_Entry) GetNumberOfHandles() int64 {
	if m != nil {
		return m.NumberOfHandles
	}
	return 0
}

type GetCategoriesRequest struct {
}

func (m *GetCategoriesRequest) Reset()                    { *m = GetCategoriesRequest{} }
func (m *GetCategoriesRequest) String() string            { return proto.CompactTextString(m) }
func (*GetCategoriesRequest) ProtoMessage()               {}
func (*GetCategoriesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type LoggerCategory struct {
	Category string `protobuf:"bytes,1,opt,name=category" json:"category,omitempty"`
	Level    uint32 `protobuf:"varint,2,opt,name=level" json:"level,omitempty"`
}

func (m *LoggerCategory) Reset()                    { *m = LoggerCategory{} }
func (m *LoggerCategory) String() string            { return proto.CompactTextString(m) }
func (*LoggerCategory) ProtoMessage()               {}
func (*LoggerCategory) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *LoggerCategory) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *LoggerCategory) GetLevel() uint32 {
	if m != nil {
		return m.Level
	}
	return 0
}

type GetCategoriesResponse struct {
	Category []*LoggerCategory `protobuf:"bytes,1,rep,name=category" json:"category,omitempty"`
}

func (m *GetCategoriesResponse) Reset()                    { *m = GetCategoriesResponse{} }
func (m *GetCategoriesResponse) String() string            { return proto.CompactTextString(m) }
func (*GetCategoriesResponse) ProtoMessage()               {}
func (*GetCategoriesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *GetCategoriesResponse) GetCategory() []*LoggerCategory {
	if m != nil {
		return m.Category
	}
	return nil
}

type SetCategoryRequest struct {
	Category string `protobuf:"bytes,1,opt,name=category" json:"category,omitempty"`
	Level    uint32 `protobuf:"varint,2,opt,name=level" json:"level,omitempty"`
}

func (m *SetCategoryRequest) Reset()                    { *m = SetCategoryRequest{} }
func (m *SetCategoryRequest) String() string            { return proto.CompactTextString(m) }
func (*SetCategoryRequest) ProtoMessage()               {}
func (*SetCategoryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *SetCategoryRequest) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *SetCategoryRequest) GetLevel() uint32 {
	if m != nil {
		return m.Level
	}
	return 0
}

type SetCategoryResponse struct {
}

func (m *SetCategoryResponse) Reset()                    { *m = SetCategoryResponse{} }
func (m *SetCategoryResponse) String() string            { return proto.CompactTextString(m) }
func (*SetCategoryResponse) ProtoMessage()               {}
func (*SetCategoryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

type GetSystemInfoRequest struct {
}

func (m *GetSystemInfoRequest) Reset()                    { *m = GetSystemInfoRequest{} }
func (m *GetSystemInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*GetSystemInfoRequest) ProtoMessage()               {}
func (*GetSystemInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

type SystemInfoResponse struct {
	GoVersion    string `protobuf:"bytes,1,opt,name=go_version,json=goVersion" json:"go_version,omitempty"`
	Os           string `protobuf:"bytes,2,opt,name=os" json:"os,omitempty"`
	Arch         string `protobuf:"bytes,3,opt,name=arch" json:"arch,omitempty"`
	NumGoroutine uint32 `protobuf:"varint,4,opt,name=num_goroutine,json=numGoroutine" json:"num_goroutine,omitempty"`
	Hostname     string `protobuf:"bytes,5,opt,name=hostname" json:"hostname,omitempty"`
	Pid          uint64 `protobuf:"varint,6,opt,name=pid" json:"pid,omitempty"`
	Uid          uint64 `protobuf:"varint,7,opt,name=uid" json:"uid,omitempty"`
	MemAlloc     uint64 `protobuf:"varint,8,opt,name=mem_alloc,json=memAlloc" json:"mem_alloc,omitempty"`
	MemSys       uint64 `protobuf:"varint,9,opt,name=mem_sys,json=memSys" json:"mem_sys,omitempty"`
	NumGc        uint32 `protobuf:"varint,10,opt,name=num_gc,json=numGc" json:"num_gc,omitempty"`
	NumFds       uint32 `protobuf:"varint,11,opt,name=num_fds,json=numFds" json:"num_fds,omitempty"`
}

func (m *SystemInfoResponse) Reset()                    { *m = SystemInfoResponse{} }
func (m *SystemInfoResponse) String() string            { return proto.CompactTextString(m) }
func (*SystemInfoResponse) ProtoMessage()               {}
func (*SystemInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *SystemInfoResponse) GetGoVersion() string {
	if m != nil {
		return m.GoVersion
	}
	return ""
}

func (m *SystemInfoResponse) GetOs() string {
	if m != nil {
		return m.Os
	}
	return ""
}

func (m *SystemInfoResponse) GetArch() string {
	if m != nil {
		return m.Arch
	}
	return ""
}

func (m *SystemInfoResponse) GetNumGoroutine() uint32 {
	if m != nil {
		return m.NumGoroutine
	}
	return 0
}

func (m *SystemInfoResponse) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *SystemInfoResponse) GetPid() uint64 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *SystemInfoResponse) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *SystemInfoResponse) GetMemAlloc() uint64 {
	if m != nil {
		return m.MemAlloc
	}
	return 0
}

func (m *SystemInfoResponse) GetMemSys() uint64 {
	if m != nil {
		return m.MemSys
	}
	return 0
}

func (m *SystemInfoResponse) GetNumGc() uint32 {
	if m != nil {
		return m.NumGc
	}
	return 0
}

func (m *SystemInfoResponse) GetNumFds() uint32 {
	if m != nil {
		return m.NumFds
	}
	return 0
}

type GetVersionRequest struct {
}

func (m *GetVersionRequest) Reset()                    { *m = GetVersionRequest{} }
func (m *GetVersionRequest) String() string            { return proto.CompactTextString(m) }
func (*GetVersionRequest) ProtoMessage()               {}
func (*GetVersionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

type VersionResponse struct {
	GitCommit string `protobuf:"bytes,1,opt,name=git_commit,json=gitCommit" json:"git_commit,omitempty"`
	BuildHost string `protobuf:"bytes,2,opt,name=build_host,json=buildHost" json:"build_host,omitempty"`
	BuildTime string `protobuf:"bytes,3,opt,name=build_time,json=buildTime" json:"build_time,omitempty"`
}

func (m *VersionResponse) Reset()                    { *m = VersionResponse{} }
func (m *VersionResponse) String() string            { return proto.CompactTextString(m) }
func (*VersionResponse) ProtoMessage()               {}
func (*VersionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *VersionResponse) GetGitCommit() string {
	if m != nil {
		return m.GitCommit
	}
	return ""
}

func (m *VersionResponse) GetBuildHost() string {
	if m != nil {
		return m.BuildHost
	}
	return ""
}

func (m *VersionResponse) GetBuildTime() string {
	if m != nil {
		return m.BuildTime
	}
	return ""
}

func init() {
	proto.RegisterType((*ListDirRequest)(nil), "pb.ListDirRequest")
	proto.RegisterType((*ListDirResponse)(nil), "pb.ListDirResponse")
	proto.RegisterType((*ListDirResponse_Entry)(nil), "pb.ListDirResponse.Entry")
	proto.RegisterType((*GetBlobstoreConfigRequest)(nil), "pb.GetBlobstoreConfigRequest")
	proto.RegisterType((*GetBlobstoreConfigResponse)(nil), "pb.GetBlobstoreConfigResponse")
	proto.RegisterType((*ReduceCacheRequest)(nil), "pb.ReduceCacheRequest")
	proto.RegisterType((*ReduceCacheResponse)(nil), "pb.ReduceCacheResponse")
	proto.RegisterType((*GetEntriesRequest)(nil), "pb.GetEntriesRequest")
	proto.RegisterType((*GetEntriesResponse)(nil), "pb.GetEntriesResponse")
	proto.RegisterType((*GetEntriesResponse_Entry)(nil), "pb.GetEntriesResponse.Entry")
	proto.RegisterType((*GetCategoriesRequest)(nil), "pb.GetCategoriesRequest")
	proto.RegisterType((*LoggerCategory)(nil), "pb.LoggerCategory")
	proto.RegisterType((*GetCategoriesResponse)(nil), "pb.GetCategoriesResponse")
	proto.RegisterType((*SetCategoryRequest)(nil), "pb.SetCategoryRequest")
	proto.RegisterType((*SetCategoryResponse)(nil), "pb.SetCategoryResponse")
	proto.RegisterType((*GetSystemInfoRequest)(nil), "pb.GetSystemInfoRequest")
	proto.RegisterType((*SystemInfoResponse)(nil), "pb.SystemInfoResponse")
	proto.RegisterType((*GetVersionRequest)(nil), "pb.GetVersionRequest")
	proto.RegisterType((*VersionResponse)(nil), "pb.VersionResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for FileSystemService service

type FileSystemServiceClient interface {
	ListDir(ctx context.Context, in *ListDirRequest, opts ...grpc.CallOption) (*ListDirResponse, error)
}

type fileSystemServiceClient struct {
	cc *grpc.ClientConn
}

func NewFileSystemServiceClient(cc *grpc.ClientConn) FileSystemServiceClient {
	return &fileSystemServiceClient{cc}
}

func (c *fileSystemServiceClient) ListDir(ctx context.Context, in *ListDirRequest, opts ...grpc.CallOption) (*ListDirResponse, error) {
	out := new(ListDirResponse)
	err := grpc.Invoke(ctx, "/pb.FileSystemService/ListDir", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FileSystemService service

type FileSystemServiceServer interface {
	ListDir(context.Context, *ListDirRequest) (*ListDirResponse, error)
}

func RegisterFileSystemServiceServer(s *grpc.Server, srv FileSystemServiceServer) {
	s.RegisterService(&_FileSystemService_serviceDesc, srv)
}

func _FileSystemService_ListDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileSystemServiceServer).ListDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.FileSystemService/ListDir",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileSystemServiceServer).ListDir(ctx, req.(*ListDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FileSystemService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.FileSystemService",
	HandlerType: (*FileSystemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListDir",
			Handler:    _FileSystemService_ListDir_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "otaru.proto",
}

// Client API for BlobstoreService service

type BlobstoreServiceClient interface {
	GetConfig(ctx context.Context, in *GetBlobstoreConfigRequest, opts ...grpc.CallOption) (*GetBlobstoreConfigResponse, error)
	GetEntries(ctx context.Context, in *GetEntriesRequest, opts ...grpc.CallOption) (*GetEntriesResponse, error)
	ReduceCache(ctx context.Context, in *ReduceCacheRequest, opts ...grpc.CallOption) (*ReduceCacheResponse, error)
}

type blobstoreServiceClient struct {
	cc *grpc.ClientConn
}

func NewBlobstoreServiceClient(cc *grpc.ClientConn) BlobstoreServiceClient {
	return &blobstoreServiceClient{cc}
}

func (c *blobstoreServiceClient) GetConfig(ctx context.Context, in *GetBlobstoreConfigRequest, opts ...grpc.CallOption) (*GetBlobstoreConfigResponse, error) {
	out := new(GetBlobstoreConfigResponse)
	err := grpc.Invoke(ctx, "/pb.BlobstoreService/GetConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blobstoreServiceClient) GetEntries(ctx context.Context, in *GetEntriesRequest, opts ...grpc.CallOption) (*GetEntriesResponse, error) {
	out := new(GetEntriesResponse)
	err := grpc.Invoke(ctx, "/pb.BlobstoreService/GetEntries", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blobstoreServiceClient) ReduceCache(ctx context.Context, in *ReduceCacheRequest, opts ...grpc.CallOption) (*ReduceCacheResponse, error) {
	out := new(ReduceCacheResponse)
	err := grpc.Invoke(ctx, "/pb.BlobstoreService/ReduceCache", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for BlobstoreService service

type BlobstoreServiceServer interface {
	GetConfig(context.Context, *GetBlobstoreConfigRequest) (*GetBlobstoreConfigResponse, error)
	GetEntries(context.Context, *GetEntriesRequest) (*GetEntriesResponse, error)
	ReduceCache(context.Context, *ReduceCacheRequest) (*ReduceCacheResponse, error)
}

func RegisterBlobstoreServiceServer(s *grpc.Server, srv BlobstoreServiceServer) {
	s.RegisterService(&_BlobstoreService_serviceDesc, srv)
}

func _BlobstoreService_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlobstoreConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlobstoreServiceServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BlobstoreService/GetConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlobstoreServiceServer).GetConfig(ctx, req.(*GetBlobstoreConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlobstoreService_GetEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlobstoreServiceServer).GetEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BlobstoreService/GetEntries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlobstoreServiceServer).GetEntries(ctx, req.(*GetEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlobstoreService_ReduceCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReduceCacheRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlobstoreServiceServer).ReduceCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BlobstoreService/ReduceCache",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlobstoreServiceServer).ReduceCache(ctx, req.(*ReduceCacheRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BlobstoreService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.BlobstoreService",
	HandlerType: (*BlobstoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConfig",
			Handler:    _BlobstoreService_GetConfig_Handler,
		},
		{
			MethodName: "GetEntries",
			Handler:    _BlobstoreService_GetEntries_Handler,
		},
		{
			MethodName: "ReduceCache",
			Handler:    _BlobstoreService_ReduceCache_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "otaru.proto",
}

// Client API for LoggerService service

type LoggerServiceClient interface {
	GetCategories(ctx context.Context, in *GetCategoriesRequest, opts ...grpc.CallOption) (*GetCategoriesResponse, error)
	SetCategory(ctx context.Context, in *SetCategoryRequest, opts ...grpc.CallOption) (*SetCategoryResponse, error)
}

type loggerServiceClient struct {
	cc *grpc.ClientConn
}

func NewLoggerServiceClient(cc *grpc.ClientConn) LoggerServiceClient {
	return &loggerServiceClient{cc}
}

func (c *loggerServiceClient) GetCategories(ctx context.Context, in *GetCategoriesRequest, opts ...grpc.CallOption) (*GetCategoriesResponse, error) {
	out := new(GetCategoriesResponse)
	err := grpc.Invoke(ctx, "/pb.LoggerService/GetCategories", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loggerServiceClient) SetCategory(ctx context.Context, in *SetCategoryRequest, opts ...grpc.CallOption) (*SetCategoryResponse, error) {
	out := new(SetCategoryResponse)
	err := grpc.Invoke(ctx, "/pb.LoggerService/SetCategory", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for LoggerService service

type LoggerServiceServer interface {
	GetCategories(context.Context, *GetCategoriesRequest) (*GetCategoriesResponse, error)
	SetCategory(context.Context, *SetCategoryRequest) (*SetCategoryResponse, error)
}

func RegisterLoggerServiceServer(s *grpc.Server, srv LoggerServiceServer) {
	s.RegisterService(&_LoggerService_serviceDesc, srv)
}

func _LoggerService_GetCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCategoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggerServiceServer).GetCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LoggerService/GetCategories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggerServiceServer).GetCategories(ctx, req.(*GetCategoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoggerService_SetCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggerServiceServer).SetCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LoggerService/SetCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggerServiceServer).SetCategory(ctx, req.(*SetCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LoggerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.LoggerService",
	HandlerType: (*LoggerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCategories",
			Handler:    _LoggerService_GetCategories_Handler,
		},
		{
			MethodName: "SetCategory",
			Handler:    _LoggerService_SetCategory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "otaru.proto",
}

// Client API for SystemInfoService service

type SystemInfoServiceClient interface {
	GetSystemInfo(ctx context.Context, in *GetSystemInfoRequest, opts ...grpc.CallOption) (*SystemInfoResponse, error)
	GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*VersionResponse, error)
}

type systemInfoServiceClient struct {
	cc *grpc.ClientConn
}

func NewSystemInfoServiceClient(cc *grpc.ClientConn) SystemInfoServiceClient {
	return &systemInfoServiceClient{cc}
}

func (c *systemInfoServiceClient) GetSystemInfo(ctx context.Context, in *GetSystemInfoRequest, opts ...grpc.CallOption) (*SystemInfoResponse, error) {
	out := new(SystemInfoResponse)
	err := grpc.Invoke(ctx, "/pb.SystemInfoService/GetSystemInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemInfoServiceClient) GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := grpc.Invoke(ctx, "/pb.SystemInfoService/GetVersion", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SystemInfoService service

type SystemInfoServiceServer interface {
	GetSystemInfo(context.Context, *GetSystemInfoRequest) (*SystemInfoResponse, error)
	GetVersion(context.Context, *GetVersionRequest) (*VersionResponse, error)
}

func RegisterSystemInfoServiceServer(s *grpc.Server, srv SystemInfoServiceServer) {
	s.RegisterService(&_SystemInfoService_serviceDesc, srv)
}

func _SystemInfoService_GetSystemInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSystemInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemInfoServiceServer).GetSystemInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SystemInfoService/GetSystemInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemInfoServiceServer).GetSystemInfo(ctx, req.(*GetSystemInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemInfoService_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemInfoServiceServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SystemInfoService/GetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemInfoServiceServer).GetVersion(ctx, req.(*GetVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SystemInfoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.SystemInfoService",
	HandlerType: (*SystemInfoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSystemInfo",
			Handler:    _SystemInfoService_GetSystemInfo_Handler,
		},
		{
			MethodName: "GetVersion",
			Handler:    _SystemInfoService_GetVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "otaru.proto",
}

func init() { proto.RegisterFile("otaru.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1338 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0xdf, 0x72, 0xdb, 0xc4,
	0x17, 0x1e, 0xdb, 0xf9, 0x63, 0x9f, 0xc4, 0x4d, 0xb3, 0xa9, 0x5b, 0xc5, 0x69, 0xf2, 0x4b, 0xd5,
	0xdf, 0x30, 0xa1, 0x50, 0x8b, 0x9a, 0x0b, 0x66, 0x72, 0x45, 0x1b, 0x48, 0xda, 0x99, 0x96, 0x16,
	0xa5, 0x05, 0xae, 0xaa, 0x91, 0xa5, 0xb5, 0xbc, 0x45, 0xd2, 0xaa, 0xda, 0x55, 0x8a, 0xcb, 0xc0,
	0x0c, 0x3c, 0x02, 0xdc, 0x71, 0xc9, 0x43, 0x30, 0xc3, 0x33, 0x30, 0x0c, 0x17, 0xbc, 0x02, 0x77,
	0xbc, 0x03, 0xc3, 0xec, 0xd9, 0x5d, 0xc7, 0x8e, 0xdd, 0x0b, 0xae, 0xb4, 0xfb, 0x9d, 0xb3, 0xdf,
	0xd9, 0x73, 0xf6, 0xec, 0xb7, 0x82, 0x35, 0x2e, 0xc3, 0xb2, 0xea, 0x15, 0x25, 0x97, 0x9c, 0xd4,
	0x8b, 0x41, 0xf7, 0x7a, 0xc2, 0x79, 0x92, 0x52, 0x2f, 0x2c, 0x98, 0x17, 0xe6, 0x39, 0x97, 0xa1,
	0x64, 0x3c, 0x17, 0xda, 0xa3, 0xfb, 0x2e, 0x7e, 0xa2, 0xdb, 0x09, 0xcd, 0x6f, 0x8b, 0x57, 0x61,
	0x92, 0xd0, 0xd2, 0xe3, 0x05, 0x7a, 0xcc, 0x7b, 0xbb, 0xff, 0x87, 0x4b, 0x0f, 0x99, 0x90, 0x1f,
	0xb1, 0xd2, 0xa7, 0x2f, 0x2b, 0x2a, 0x24, 0x21, 0xb0, 0x54, 0x84, 0x72, 0xe4, 0xd4, 0xf6, 0x6b,
	0x07, 0x2d, 0x1f, 0xc7, 0xee, 0x3f, 0x35, 0xd8, 0x98, 0xb8, 0x89, 0x82, 0xe7, 0x82, 0x12, 0x0f,
	0x96, 0x69, 0x2e, 0xcb, 0xb1, 0x53, 0xdb, 0x6f, 0x1c, 0xac, 0xf5, 0xb7, 0x7b, 0xc5, 0xa0, 0x77,
	0xc1, 0xa7, 0xf7, 0xb1, 0x72, 0xf0, 0xb5, 0x5f, 0xf7, 0xd7, 0x1a, 0x2c, 0x23, 0x40, 0x2e, 0x41,
	0x9d, 0xc5, 0x18, 0x60, 0xc9, 0xaf, 0xb3, 0x58, 0x85, 0xcc, 0xc3, 0x8c, 0x3a, 0x75, 0x1d, 0x52,
	0x8d, 0x15, 0x26, 0xc7, 0x05, 0x75, 0x1a, 0x1a, 0x53, 0x63, 0x85, 0x09, 0xf6, 0x9a, 0x3a, 0x4b,
	0xfb, 0xb5, 0x83, 0x86, 0x8f, 0x63, 0x72, 0x19, 0x1a, 0x15, 0x8b, 0x9d, 0xe5, 0xfd, 0xda, 0x41,
	0xdb, 0x57, 0x43, 0x85, 0x24, 0x2c, 0x76, 0x56, 0x34, 0x92, 0xb0, 0x98, 0xec, 0x40, 0xab, 0xa0,
	0x65, 0x16, 0x64, 0x3c, 0xa6, 0xce, 0x2a, 0xe2, 0x4d, 0x05, 0x3c, 0xe2, 0x31, 0x25, 0x37, 0xa1,
	0x9d, 0xf1, 0x98, 0x0d, 0x19, 0x8d, 0x03, 0xc9, 0x32, 0xea, 0x34, 0x91, 0x7d, 0xdd, 0x82, 0x4f,
	0x59, 0x46, 0xdd, 0x1d, 0xd8, 0x3e, 0xa1, 0xf2, 0x5e, 0xca, 0x07, 0x42, 0xf2, 0x92, 0x1e, 0xf1,
	0x7c, 0xc8, 0x12, 0x53, 0x31, 0xf7, 0x97, 0x1a, 0x74, 0x17, 0x59, 0x4d, 0xa1, 0x6e, 0xc1, 0xe6,
	0x20, 0x8c, 0xbe, 0xa4, 0x79, 0x1c, 0xb0, 0xac, 0x48, 0x03, 0x4c, 0x55, 0x57, 0x77, 0xc3, 0x18,
	0x1e, 0x64, 0x45, 0xfa, 0x89, 0xca, 0xfa, 0x26, 0xb4, 0xad, 0xef, 0x30, 0x0d, 0x13, 0x61, 0x4a,
	0xb2, 0x6e, 0xc0, 0x63, 0x85, 0x91, 0xb7, 0x60, 0x23, 0x0a, 0xa3, 0x11, 0x9d, 0xa2, 0xd3, 0x55,
	0x6a, 0x23, 0x3c, 0x21, 0xfb, 0x1f, 0xac, 0x69, 0x3f, 0x4d, 0xb5, 0x84, 0x3e, 0x80, 0x10, 0x12,
	0xb9, 0x4f, 0x80, 0xf8, 0x34, 0xae, 0x22, 0x7a, 0xa4, 0x30, 0xdb, 0x00, 0xd7, 0x60, 0x35, 0x2e,
	0xc7, 0x41, 0x59, 0xe5, 0xb8, 0xcb, 0xa6, 0xbf, 0x12, 0x97, 0x63, 0xbf, 0xca, 0xc9, 0x0d, 0x58,
	0x8f, 0xa9, 0x60, 0x25, 0x8d, 0x03, 0x3c, 0x06, 0xbd, 0xb7, 0x35, 0x83, 0x9d, 0xb2, 0xd7, 0xd4,
	0x7d, 0x0a, 0x5b, 0x33, 0x8c, 0xa6, 0x04, 0x0e, 0xac, 0x8a, 0x2a, 0x8a, 0xa8, 0x10, 0x86, 0xd2,
	0x4e, 0x55, 0xc2, 0xb4, 0x2c, 0x79, 0x19, 0x64, 0x54, 0x88, 0x30, 0xb1, 0xa4, 0xeb, 0x08, 0x3e,
	0xd2, 0x98, 0xbb, 0x05, 0x9b, 0x27, 0x54, 0xaa, 0xde, 0x61, 0x54, 0xd8, 0xaa, 0xff, 0xd4, 0x00,
	0x32, 0x8d, 0x9a, 0x50, 0xfd, 0xd9, 0xb6, 0xbc, 0xae, 0xda, 0x72, 0xde, 0x6d, 0xb6, 0x33, 0xff,
	0xa8, 0xdb, 0xce, 0xdc, 0x81, 0xd6, 0x20, 0xe5, 0x83, 0x60, 0xea, 0x06, 0x34, 0x15, 0xf0, 0x24,
	0x94, 0x23, 0x72, 0x05, 0x96, 0x85, 0x0c, 0xa5, 0xdd, 0xa3, 0x9e, 0x90, 0x6d, 0x40, 0x8f, 0x20,
	0xa5, 0x39, 0x1e, 0x43, 0xc3, 0x5f, 0x55, 0xf3, 0x87, 0x34, 0x57, 0x6c, 0x67, 0x61, 0xca, 0x62,
	0xb4, 0xe9, 0xa6, 0x6d, 0x22, 0xa0, 0x8c, 0xbb, 0x00, 0x62, 0x9c, 0x47, 0x41, 0xc4, 0xab, 0x5c,
	0x62, 0xff, 0x36, 0xfc, 0x96, 0x42, 0x8e, 0x14, 0xa0, 0xd6, 0xa6, 0xa1, 0x90, 0x41, 0x25, 0xa8,
	0xee, 0xe5, 0x86, 0xdf, 0x54, 0xc0, 0x33, 0x41, 0x63, 0xb5, 0x16, 0x8d, 0xaf, 0x4a, 0x26, 0x75,
	0x47, 0x37, 0x7c, 0x74, 0xff, 0x5c, 0x01, 0x93, 0xb5, 0x8a, 0xcd, 0xb4, 0x33, 0xae, 0x3d, 0x1d,
	0xe7, 0x11, 0xf9, 0x00, 0x9c, 0xbc, 0xca, 0x06, 0xb4, 0x0c, 0xf8, 0x50, 0x13, 0x94, 0xc1, 0x28,
	0xcc, 0xe3, 0x94, 0x0a, 0xa7, 0x85, 0xbe, 0x1d, 0x6d, 0x7f, 0x3c, 0x44, 0xb6, 0xf2, 0xbe, 0x36,
	0xaa, 0x3e, 0x3e, 0x5f, 0x68, 0x57, 0x00, 0xae, 0xd8, 0xb0, 0x2b, 0x8c, 0xaf, 0x7b, 0x15, 0xae,
	0x9c, 0x50, 0x79, 0x14, 0x4a, 0x9a, 0xf0, 0xe9, 0x43, 0xbb, 0x07, 0x97, 0x1e, 0x72, 0x25, 0x49,
	0xc6, 0x34, 0x26, 0x5d, 0x68, 0x46, 0x66, 0x6c, 0x0b, 0x6e, 0xe7, 0xaa, 0xe0, 0x29, 0x3d, 0xa3,
	0x29, 0x16, 0xbc, 0xed, 0xeb, 0x89, 0x7b, 0x02, 0x9d, 0x0b, 0xdc, 0xe6, 0xe8, 0x7b, 0x33, 0x54,
	0xea, 0xf4, 0x09, 0x8a, 0xd2, 0x4c, 0xc0, 0x73, 0x7a, 0xf7, 0x18, 0xc8, 0xe9, 0x84, 0x68, 0x6c,
	0xdb, 0xff, 0xbf, 0x6f, 0xa8, 0x03, 0x5b, 0x33, 0x3c, 0x7a, 0x3b, 0xa6, 0x06, 0xa7, 0x63, 0x21,
	0x69, 0xf6, 0x20, 0x1f, 0x72, 0x5b, 0x83, 0x9f, 0xeb, 0x40, 0xa6, 0x51, 0xb3, 0xfb, 0x5d, 0x80,
	0x84, 0x07, 0x67, 0xb4, 0x14, 0x8c, 0xe7, 0x26, 0x72, 0x2b, 0xe1, 0x9f, 0x69, 0x40, 0x69, 0x26,
	0xb7, 0x72, 0x50, 0xe7, 0x42, 0x69, 0x61, 0x58, 0x46, 0x23, 0xab, 0x8f, 0x6a, 0xac, 0x2e, 0x53,
	0x5e, 0x65, 0x41, 0xc2, 0x4b, 0x5e, 0x49, 0x96, 0x6b, 0xa1, 0x6c, 0xfb, 0xeb, 0x79, 0x95, 0x9d,
	0x58, 0x4c, 0xe5, 0x37, 0xe2, 0x42, 0xa2, 0x6c, 0x2c, 0xeb, 0xfc, 0xec, 0x5c, 0x49, 0x67, 0x61,
	0xa4, 0x73, 0xc9, 0x57, 0x43, 0x2b, 0xaf, 0xab, 0x1a, 0xa9, 0xb4, 0x98, 0x66, 0x34, 0x0b, 0xc2,
	0x34, 0xe5, 0xba, 0xb9, 0x96, 0xfc, 0x66, 0x46, 0xb3, 0xbb, 0x6a, 0xae, 0xb4, 0x43, 0x19, 0xc5,
	0x58, 0xf7, 0xd2, 0x92, 0xbf, 0x92, 0xd1, 0xec, 0x74, 0x2c, 0x48, 0x07, 0x56, 0x70, 0x6b, 0x11,
	0x76, 0x4c, 0xdb, 0x5f, 0x56, 0x7b, 0x42, 0x7f, 0x05, 0x0f, 0x63, 0xe1, 0xac, 0x21, 0xae, 0xbc,
	0x8e, 0x63, 0x61, 0xae, 0xbc, 0x49, 0xde, 0x56, 0x2e, 0x87, 0x8d, 0x09, 0x32, 0x55, 0x35, 0x26,
	0x83, 0x88, 0x67, 0x19, 0x93, 0x93, 0xaa, 0x31, 0x79, 0x84, 0x80, 0x32, 0x0f, 0x2a, 0x96, 0xc6,
	0x81, 0x4a, 0xd1, 0x54, 0xaf, 0x85, 0xc8, 0x7d, 0x2e, 0xa6, 0xcc, 0x28, 0xfc, 0x8d, 0x29, 0xb3,
	0x52, 0xfd, 0xfe, 0x10, 0x36, 0x8f, 0x59, 0x4a, 0xf5, 0x61, 0x9d, 0xd2, 0xf2, 0x8c, 0x45, 0x94,
	0x7c, 0x0a, 0xab, 0xe6, 0x99, 0x23, 0x64, 0xe6, 0xcd, 0xc3, 0x3d, 0x76, 0xb7, 0x16, 0xbc, 0x83,
	0xee, 0xee, 0xf7, 0x7f, 0xfe, 0xf5, 0x63, 0xfd, 0x1a, 0xe9, 0xe0, 0x9b, 0x7d, 0x76, 0xc7, 0x1b,
	0xb2, 0x94, 0x0a, 0xa4, 0xf5, 0x52, 0xd1, 0xff, 0xad, 0x0e, 0x97, 0x27, 0xaf, 0x87, 0x8d, 0x93,
	0x42, 0x4b, 0xb5, 0x39, 0xbe, 0x25, 0x64, 0xd7, 0xc8, 0xd8, 0xe2, 0x17, 0xa8, 0xbb, 0xf7, 0x26,
	0xb3, 0x89, 0xbf, 0x8f, 0xf1, 0xbb, 0xc4, 0xb1, 0xf1, 0x07, 0xd6, 0xd1, 0x8b, 0x74, 0x80, 0xe7,
	0x00, 0xe7, 0x2a, 0x49, 0x3a, 0x17, 0x55, 0x53, 0x87, 0xb9, 0xba, 0x58, 0x4c, 0xdd, 0x1b, 0x48,
	0xbf, 0x43, 0xb6, 0xe7, 0xe9, 0xa9, 0x61, 0x64, 0xb0, 0x36, 0xf5, 0x30, 0x10, 0x64, 0x9a, 0x7f,
	0x7b, 0xba, 0xd7, 0xe6, 0x70, 0x13, 0xe2, 0x6d, 0x0c, 0x71, 0xd3, 0xdd, 0x9b, 0x0f, 0x51, 0xa2,
	0x7b, 0x80, 0xef, 0xda, 0x61, 0xed, 0x56, 0xff, 0xef, 0x1a, 0xb4, 0xf5, 0x9d, 0xb7, 0xa5, 0x4c,
	0xa0, 0x3d, 0xa3, 0x18, 0xc4, 0x31, 0x89, 0xcc, 0x09, 0x54, 0x77, 0x7b, 0x81, 0xe5, 0x4d, 0x59,
	0xa6, 0x18, 0xc4, 0x8b, 0xce, 0x79, 0x5f, 0xc2, 0xda, 0x94, 0x12, 0xe8, 0x2c, 0xe7, 0x25, 0x46,
	0x67, 0xb9, 0x48, 0x32, 0xee, 0x60, 0x88, 0x77, 0x5c, 0x77, 0x71, 0x88, 0xb1, 0xf7, 0xb5, 0x1d,
	0x7d, 0x73, 0xa8, 0xc5, 0xa7, 0xff, 0x7b, 0x0d, 0x36, 0xcf, 0xd5, 0xc4, 0x66, 0xfc, 0x1c, 0x33,
	0x3e, 0xc7, 0x27, 0x19, 0xcf, 0xc9, 0x91, 0x3e, 0xd4, 0x79, 0x3d, 0x72, 0x77, 0x70, 0x2f, 0x1d,
	0xb2, 0x65, 0xf7, 0x62, 0xfa, 0x95, 0x29, 0xba, 0x2f, 0xb0, 0x5d, 0xac, 0x36, 0xd9, 0x76, 0x99,
	0xbd, 0xae, 0xfa, 0x2a, 0x5c, 0xb8, 0xb0, 0xee, 0x1e, 0xd2, 0x3a, 0xe4, 0xea, 0x05, 0x5a, 0x23,
	0x7c, 0xf7, 0xbe, 0xab, 0xfd, 0x70, 0xf7, 0x5b, 0xf2, 0x0c, 0x5a, 0x8f, 0xd5, 0x5f, 0xef, 0xfe,
	0xdd, 0x27, 0x0f, 0xdc, 0x23, 0x68, 0xeb, 0x49, 0x51, 0xf2, 0x17, 0x34, 0x92, 0x64, 0x6f, 0x24,
	0x65, 0x21, 0x0e, 0x3d, 0x2f, 0x61, 0x72, 0x54, 0x0d, 0x7a, 0x11, 0xcf, 0xbc, 0x7c, 0x1c, 0x7e,
	0x25, 0x3d, 0xfc, 0x55, 0xee, 0x92, 0x8a, 0xe6, 0xfc, 0x43, 0x44, 0x84, 0xa4, 0x85, 0xb2, 0xf7,
	0x1b, 0x77, 0x7a, 0xef, 0xdd, 0xaa, 0xd5, 0xfb, 0x97, 0xc3, 0xa2, 0x48, 0x59, 0x84, 0x3f, 0xc1,
	0xde, 0x0b, 0xc1, 0xf3, 0xc3, 0x39, 0x64, 0xb0, 0x82, 0xff, 0xc6, 0xef, 0xff, 0x1b, 0x00, 0x00,
	0xff, 0xff, 0x78, 0x01, 0x04, 0x9d, 0x7a, 0x0b, 0x00, 0x00,
}
