// Code generated by protoc-gen-go. DO NOT EDIT.
// source: system.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	system.proto

It has these top-level messages:
	GetSystemInfoRequest
	SystemInfoResponse
	GetVersionRequest
	VersionResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetSystemInfoRequest struct {
}

func (m *GetSystemInfoRequest) Reset()                    { *m = GetSystemInfoRequest{} }
func (m *GetSystemInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*GetSystemInfoRequest) ProtoMessage()               {}
func (*GetSystemInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type SystemInfoResponse struct {
	GoVersion    string `protobuf:"bytes,1,opt,name=go_version,json=goVersion" json:"go_version,omitempty"`
	Os           string `protobuf:"bytes,2,opt,name=os" json:"os,omitempty"`
	Arch         string `protobuf:"bytes,3,opt,name=arch" json:"arch,omitempty"`
	NumGoroutine uint32 `protobuf:"varint,4,opt,name=num_goroutine,json=numGoroutine" json:"num_goroutine,omitempty"`
	Hostname     string `protobuf:"bytes,5,opt,name=hostname" json:"hostname,omitempty"`
	Pid          uint64 `protobuf:"varint,6,opt,name=pid" json:"pid,omitempty"`
	Uid          uint64 `protobuf:"varint,7,opt,name=uid" json:"uid,omitempty"`
	MemAlloc     uint64 `protobuf:"varint,8,opt,name=mem_alloc,json=memAlloc" json:"mem_alloc,omitempty"`
	MemSys       uint64 `protobuf:"varint,9,opt,name=mem_sys,json=memSys" json:"mem_sys,omitempty"`
	NumGc        uint32 `protobuf:"varint,10,opt,name=num_gc,json=numGc" json:"num_gc,omitempty"`
	NumFds       uint32 `protobuf:"varint,11,opt,name=num_fds,json=numFds" json:"num_fds,omitempty"`
}

func (m *SystemInfoResponse) Reset()                    { *m = SystemInfoResponse{} }
func (m *SystemInfoResponse) String() string            { return proto.CompactTextString(m) }
func (*SystemInfoResponse) ProtoMessage()               {}
func (*SystemInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SystemInfoResponse) GetGoVersion() string {
	if m != nil {
		return m.GoVersion
	}
	return ""
}

func (m *SystemInfoResponse) GetOs() string {
	if m != nil {
		return m.Os
	}
	return ""
}

func (m *SystemInfoResponse) GetArch() string {
	if m != nil {
		return m.Arch
	}
	return ""
}

func (m *SystemInfoResponse) GetNumGoroutine() uint32 {
	if m != nil {
		return m.NumGoroutine
	}
	return 0
}

func (m *SystemInfoResponse) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *SystemInfoResponse) GetPid() uint64 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *SystemInfoResponse) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *SystemInfoResponse) GetMemAlloc() uint64 {
	if m != nil {
		return m.MemAlloc
	}
	return 0
}

func (m *SystemInfoResponse) GetMemSys() uint64 {
	if m != nil {
		return m.MemSys
	}
	return 0
}

func (m *SystemInfoResponse) GetNumGc() uint32 {
	if m != nil {
		return m.NumGc
	}
	return 0
}

func (m *SystemInfoResponse) GetNumFds() uint32 {
	if m != nil {
		return m.NumFds
	}
	return 0
}

type GetVersionRequest struct {
}

func (m *GetVersionRequest) Reset()                    { *m = GetVersionRequest{} }
func (m *GetVersionRequest) String() string            { return proto.CompactTextString(m) }
func (*GetVersionRequest) ProtoMessage()               {}
func (*GetVersionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type VersionResponse struct {
	GitCommit string `protobuf:"bytes,1,opt,name=git_commit,json=gitCommit" json:"git_commit,omitempty"`
	BuildHost string `protobuf:"bytes,2,opt,name=build_host,json=buildHost" json:"build_host,omitempty"`
	BuildTime string `protobuf:"bytes,3,opt,name=build_time,json=buildTime" json:"build_time,omitempty"`
}

func (m *VersionResponse) Reset()                    { *m = VersionResponse{} }
func (m *VersionResponse) String() string            { return proto.CompactTextString(m) }
func (*VersionResponse) ProtoMessage()               {}
func (*VersionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *VersionResponse) GetGitCommit() string {
	if m != nil {
		return m.GitCommit
	}
	return ""
}

func (m *VersionResponse) GetBuildHost() string {
	if m != nil {
		return m.BuildHost
	}
	return ""
}

func (m *VersionResponse) GetBuildTime() string {
	if m != nil {
		return m.BuildTime
	}
	return ""
}

func init() {
	proto.RegisterType((*GetSystemInfoRequest)(nil), "pb.GetSystemInfoRequest")
	proto.RegisterType((*SystemInfoResponse)(nil), "pb.SystemInfoResponse")
	proto.RegisterType((*GetVersionRequest)(nil), "pb.GetVersionRequest")
	proto.RegisterType((*VersionResponse)(nil), "pb.VersionResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SystemInfoService service

type SystemInfoServiceClient interface {
	GetSystemInfo(ctx context.Context, in *GetSystemInfoRequest, opts ...grpc.CallOption) (*SystemInfoResponse, error)
	GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*VersionResponse, error)
}

type systemInfoServiceClient struct {
	cc *grpc.ClientConn
}

func NewSystemInfoServiceClient(cc *grpc.ClientConn) SystemInfoServiceClient {
	return &systemInfoServiceClient{cc}
}

func (c *systemInfoServiceClient) GetSystemInfo(ctx context.Context, in *GetSystemInfoRequest, opts ...grpc.CallOption) (*SystemInfoResponse, error) {
	out := new(SystemInfoResponse)
	err := grpc.Invoke(ctx, "/pb.SystemInfoService/GetSystemInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemInfoServiceClient) GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := grpc.Invoke(ctx, "/pb.SystemInfoService/GetVersion", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SystemInfoService service

type SystemInfoServiceServer interface {
	GetSystemInfo(context.Context, *GetSystemInfoRequest) (*SystemInfoResponse, error)
	GetVersion(context.Context, *GetVersionRequest) (*VersionResponse, error)
}

func RegisterSystemInfoServiceServer(s *grpc.Server, srv SystemInfoServiceServer) {
	s.RegisterService(&_SystemInfoService_serviceDesc, srv)
}

func _SystemInfoService_GetSystemInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSystemInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemInfoServiceServer).GetSystemInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SystemInfoService/GetSystemInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemInfoServiceServer).GetSystemInfo(ctx, req.(*GetSystemInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemInfoService_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemInfoServiceServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SystemInfoService/GetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemInfoServiceServer).GetVersion(ctx, req.(*GetVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SystemInfoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.SystemInfoService",
	HandlerType: (*SystemInfoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSystemInfo",
			Handler:    _SystemInfoService_GetSystemInfo_Handler,
		},
		{
			MethodName: "GetVersion",
			Handler:    _SystemInfoService_GetVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "system.proto",
}

func init() { proto.RegisterFile("system.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 428 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0x65, 0x37, 0x4d, 0xe3, 0xa1, 0x01, 0x3a, 0x21, 0x61, 0x95, 0x02, 0x8a, 0xcc, 0x25,
	0xa7, 0x44, 0xc0, 0x13, 0x20, 0x24, 0x02, 0xd7, 0x04, 0x21, 0x4e, 0x58, 0x8e, 0x3d, 0x75, 0x57,
	0xf2, 0xee, 0x18, 0xef, 0x3a, 0x52, 0xae, 0xbc, 0x02, 0x6f, 0xc0, 0xfb, 0x70, 0xe2, 0x15, 0x78,
	0x10, 0xb4, 0x6b, 0x37, 0x4d, 0x0b, 0xb7, 0xdd, 0xef, 0x9f, 0x19, 0xcd, 0xfc, 0x33, 0x70, 0x6e,
	0xf6, 0xc6, 0x92, 0x5a, 0x54, 0x35, 0x5b, 0xc6, 0xb0, 0xda, 0x4e, 0x9f, 0x15, 0xcc, 0x45, 0x49,
	0xcb, 0xb4, 0x92, 0xcb, 0x54, 0x6b, 0xb6, 0xa9, 0x95, 0xac, 0x4d, 0x1b, 0x11, 0x4f, 0xe0, 0xc9,
	0x8a, 0xec, 0xc6, 0x27, 0x7d, 0xd4, 0x57, 0xbc, 0xa6, 0x6f, 0x0d, 0x19, 0x1b, 0xff, 0x0c, 0x01,
	0x8f, 0xa9, 0xa9, 0x58, 0x1b, 0xc2, 0xe7, 0x00, 0x05, 0x27, 0x3b, 0xaa, 0x8d, 0x64, 0x2d, 0x82,
	0x59, 0x30, 0x8f, 0xd6, 0x51, 0xc1, 0x9f, 0x5b, 0x80, 0x0f, 0x21, 0x64, 0x23, 0x42, 0x8f, 0x43,
	0x36, 0x88, 0xd0, 0x4b, 0xeb, 0xec, 0x5a, 0x9c, 0x78, 0xe2, 0xdf, 0xf8, 0x12, 0x86, 0xba, 0x51,
	0x49, 0xc1, 0x35, 0x37, 0x56, 0x6a, 0x12, 0xbd, 0x59, 0x30, 0x1f, 0xae, 0xcf, 0x75, 0xa3, 0x56,
	0x37, 0x0c, 0xa7, 0x30, 0xb8, 0x66, 0x63, 0x75, 0xaa, 0x48, 0x9c, 0xfa, 0xe4, 0xc3, 0x1f, 0x1f,
	0xc3, 0x49, 0x25, 0x73, 0xd1, 0x9f, 0x05, 0xf3, 0xde, 0xda, 0x3d, 0x1d, 0x69, 0x64, 0x2e, 0xce,
	0x5a, 0xd2, 0xc8, 0x1c, 0x2f, 0x21, 0x52, 0xa4, 0x92, 0xb4, 0x2c, 0x39, 0x13, 0x03, 0xcf, 0x07,
	0x8a, 0xd4, 0x5b, 0xf7, 0xc7, 0xa7, 0x70, 0xe6, 0x44, 0xb3, 0x37, 0x22, 0xf2, 0x52, 0x5f, 0x91,
	0xda, 0xec, 0x0d, 0x8e, 0xa1, 0xef, 0x5b, 0xcb, 0x04, 0xf8, 0x9e, 0x4e, 0x5d, 0x4f, 0x3e, 0xde,
	0xe1, 0xab, 0xdc, 0x88, 0x07, 0x9e, 0xbb, 0xa8, 0xf7, 0xb9, 0x89, 0x47, 0x70, 0xb1, 0x22, 0xdb,
	0x0d, 0x7f, 0xe3, 0x9c, 0x86, 0x47, 0x07, 0x72, 0xe4, 0x9a, 0xb4, 0x49, 0xc6, 0x4a, 0x49, 0x7b,
	0x70, 0x4d, 0xda, 0x77, 0x1e, 0x38, 0x79, 0xdb, 0xc8, 0x32, 0x4f, 0xdc, 0x88, 0x9d, 0x7b, 0x91,
	0x27, 0x1f, 0xd8, 0x1c, 0xc9, 0x56, 0x2a, 0xea, 0xac, 0x6c, 0xe5, 0x4f, 0x52, 0xd1, 0xeb, 0x5f,
	0x01, 0x5c, 0xdc, 0x6e, 0x6a, 0x43, 0xf5, 0x4e, 0x66, 0x84, 0x5f, 0x61, 0x78, 0x67, 0xaf, 0x28,
	0x16, 0xd5, 0x76, 0xf1, 0xbf, 0x55, 0x4f, 0x27, 0x4e, 0xf9, 0x77, 0xd7, 0xf1, 0xe5, 0xf7, 0xdf,
	0x7f, 0x7e, 0x84, 0x63, 0x1c, 0xf9, 0xd3, 0xd9, 0xbd, 0x5a, 0xb6, 0xa7, 0xb5, 0x94, 0xae, 0xdc,
	0x17, 0x80, 0xdb, 0xd1, 0x71, 0xdc, 0x15, 0xbf, 0x6b, 0xc5, 0x74, 0xe4, 0xf0, 0x3d, 0x33, 0xe2,
	0x17, 0xbe, 0xac, 0xc0, 0xc9, 0xbd, 0xb2, 0xdd, 0x51, 0x6d, 0xfb, 0xfe, 0x30, 0xdf, 0xfc, 0x0d,
	0x00, 0x00, 0xff, 0xff, 0x86, 0x5f, 0xc6, 0xeb, 0xca, 0x02, 0x00, 0x00,
}
