// Code generated by protoc-gen-go. DO NOT EDIT.
// source: otaru-fe.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
import pb "github.com/nyaxt/otaru/pb"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ListHostsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListHostsRequest) Reset()         { *m = ListHostsRequest{} }
func (m *ListHostsRequest) String() string { return proto.CompactTextString(m) }
func (*ListHostsRequest) ProtoMessage()    {}
func (*ListHostsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_otaru_fe_dd9b886daca14798, []int{0}
}
func (m *ListHostsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListHostsRequest.Unmarshal(m, b)
}
func (m *ListHostsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListHostsRequest.Marshal(b, m, deterministic)
}
func (dst *ListHostsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListHostsRequest.Merge(dst, src)
}
func (m *ListHostsRequest) XXX_Size() int {
	return xxx_messageInfo_ListHostsRequest.Size(m)
}
func (m *ListHostsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListHostsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListHostsRequest proto.InternalMessageInfo

type ListHostsResponse struct {
	Host                 []string `protobuf:"bytes,1,rep,name=host,proto3" json:"host,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListHostsResponse) Reset()         { *m = ListHostsResponse{} }
func (m *ListHostsResponse) String() string { return proto.CompactTextString(m) }
func (*ListHostsResponse) ProtoMessage()    {}
func (*ListHostsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_otaru_fe_dd9b886daca14798, []int{1}
}
func (m *ListHostsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListHostsResponse.Unmarshal(m, b)
}
func (m *ListHostsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListHostsResponse.Marshal(b, m, deterministic)
}
func (dst *ListHostsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListHostsResponse.Merge(dst, src)
}
func (m *ListHostsResponse) XXX_Size() int {
	return xxx_messageInfo_ListHostsResponse.Size(m)
}
func (m *ListHostsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListHostsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListHostsResponse proto.InternalMessageInfo

func (m *ListHostsResponse) GetHost() []string {
	if m != nil {
		return m.Host
	}
	return nil
}

type FileInfo struct {
	Name                 string       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 pb.INodeType `protobuf:"varint,2,opt,name=type,proto3,enum=pb.INodeType" json:"type,omitempty"`
	Size                 int64        `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	PermMode             uint32       `protobuf:"varint,4,opt,name=perm_mode,json=permMode,proto3" json:"perm_mode,omitempty"`
	ModifiedTime         int64        `protobuf:"varint,5,opt,name=modified_time,json=modifiedTime,proto3" json:"modified_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *FileInfo) Reset()         { *m = FileInfo{} }
func (m *FileInfo) String() string { return proto.CompactTextString(m) }
func (*FileInfo) ProtoMessage()    {}
func (*FileInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_otaru_fe_dd9b886daca14798, []int{2}
}
func (m *FileInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileInfo.Unmarshal(m, b)
}
func (m *FileInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileInfo.Marshal(b, m, deterministic)
}
func (dst *FileInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileInfo.Merge(dst, src)
}
func (m *FileInfo) XXX_Size() int {
	return xxx_messageInfo_FileInfo.Size(m)
}
func (m *FileInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FileInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FileInfo proto.InternalMessageInfo

func (m *FileInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FileInfo) GetType() pb.INodeType {
	if m != nil {
		return m.Type
	}
	return pb.INodeType_FILE
}

func (m *FileInfo) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *FileInfo) GetPermMode() uint32 {
	if m != nil {
		return m.PermMode
	}
	return 0
}

func (m *FileInfo) GetModifiedTime() int64 {
	if m != nil {
		return m.ModifiedTime
	}
	return 0
}

type ListLocalDirRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListLocalDirRequest) Reset()         { *m = ListLocalDirRequest{} }
func (m *ListLocalDirRequest) String() string { return proto.CompactTextString(m) }
func (*ListLocalDirRequest) ProtoMessage()    {}
func (*ListLocalDirRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_otaru_fe_dd9b886daca14798, []int{3}
}
func (m *ListLocalDirRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListLocalDirRequest.Unmarshal(m, b)
}
func (m *ListLocalDirRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListLocalDirRequest.Marshal(b, m, deterministic)
}
func (dst *ListLocalDirRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListLocalDirRequest.Merge(dst, src)
}
func (m *ListLocalDirRequest) XXX_Size() int {
	return xxx_messageInfo_ListLocalDirRequest.Size(m)
}
func (m *ListLocalDirRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListLocalDirRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListLocalDirRequest proto.InternalMessageInfo

func (m *ListLocalDirRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type ListLocalDirResponse struct {
	Entry                []*FileInfo `protobuf:"bytes,1,rep,name=entry,proto3" json:"entry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListLocalDirResponse) Reset()         { *m = ListLocalDirResponse{} }
func (m *ListLocalDirResponse) String() string { return proto.CompactTextString(m) }
func (*ListLocalDirResponse) ProtoMessage()    {}
func (*ListLocalDirResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_otaru_fe_dd9b886daca14798, []int{4}
}
func (m *ListLocalDirResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListLocalDirResponse.Unmarshal(m, b)
}
func (m *ListLocalDirResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListLocalDirResponse.Marshal(b, m, deterministic)
}
func (dst *ListLocalDirResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListLocalDirResponse.Merge(dst, src)
}
func (m *ListLocalDirResponse) XXX_Size() int {
	return xxx_messageInfo_ListLocalDirResponse.Size(m)
}
func (m *ListLocalDirResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListLocalDirResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListLocalDirResponse proto.InternalMessageInfo

func (m *ListLocalDirResponse) GetEntry() []*FileInfo {
	if m != nil {
		return m.Entry
	}
	return nil
}

type MkdirLocalRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MkdirLocalRequest) Reset()         { *m = MkdirLocalRequest{} }
func (m *MkdirLocalRequest) String() string { return proto.CompactTextString(m) }
func (*MkdirLocalRequest) ProtoMessage()    {}
func (*MkdirLocalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_otaru_fe_dd9b886daca14798, []int{5}
}
func (m *MkdirLocalRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MkdirLocalRequest.Unmarshal(m, b)
}
func (m *MkdirLocalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MkdirLocalRequest.Marshal(b, m, deterministic)
}
func (dst *MkdirLocalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MkdirLocalRequest.Merge(dst, src)
}
func (m *MkdirLocalRequest) XXX_Size() int {
	return xxx_messageInfo_MkdirLocalRequest.Size(m)
}
func (m *MkdirLocalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MkdirLocalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MkdirLocalRequest proto.InternalMessageInfo

func (m *MkdirLocalRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type MkdirLocalResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MkdirLocalResponse) Reset()         { *m = MkdirLocalResponse{} }
func (m *MkdirLocalResponse) String() string { return proto.CompactTextString(m) }
func (*MkdirLocalResponse) ProtoMessage()    {}
func (*MkdirLocalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_otaru_fe_dd9b886daca14798, []int{6}
}
func (m *MkdirLocalResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MkdirLocalResponse.Unmarshal(m, b)
}
func (m *MkdirLocalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MkdirLocalResponse.Marshal(b, m, deterministic)
}
func (dst *MkdirLocalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MkdirLocalResponse.Merge(dst, src)
}
func (m *MkdirLocalResponse) XXX_Size() int {
	return xxx_messageInfo_MkdirLocalResponse.Size(m)
}
func (m *MkdirLocalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MkdirLocalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MkdirLocalResponse proto.InternalMessageInfo

type MoveLocalRequest struct {
	PathSrc              string   `protobuf:"bytes,1,opt,name=path_src,json=pathSrc,proto3" json:"path_src,omitempty"`
	PathDest             string   `protobuf:"bytes,2,opt,name=path_dest,json=pathDest,proto3" json:"path_dest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveLocalRequest) Reset()         { *m = MoveLocalRequest{} }
func (m *MoveLocalRequest) String() string { return proto.CompactTextString(m) }
func (*MoveLocalRequest) ProtoMessage()    {}
func (*MoveLocalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_otaru_fe_dd9b886daca14798, []int{7}
}
func (m *MoveLocalRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveLocalRequest.Unmarshal(m, b)
}
func (m *MoveLocalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveLocalRequest.Marshal(b, m, deterministic)
}
func (dst *MoveLocalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveLocalRequest.Merge(dst, src)
}
func (m *MoveLocalRequest) XXX_Size() int {
	return xxx_messageInfo_MoveLocalRequest.Size(m)
}
func (m *MoveLocalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveLocalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MoveLocalRequest proto.InternalMessageInfo

func (m *MoveLocalRequest) GetPathSrc() string {
	if m != nil {
		return m.PathSrc
	}
	return ""
}

func (m *MoveLocalRequest) GetPathDest() string {
	if m != nil {
		return m.PathDest
	}
	return ""
}

type MoveLocalResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveLocalResponse) Reset()         { *m = MoveLocalResponse{} }
func (m *MoveLocalResponse) String() string { return proto.CompactTextString(m) }
func (*MoveLocalResponse) ProtoMessage()    {}
func (*MoveLocalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_otaru_fe_dd9b886daca14798, []int{8}
}
func (m *MoveLocalResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveLocalResponse.Unmarshal(m, b)
}
func (m *MoveLocalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveLocalResponse.Marshal(b, m, deterministic)
}
func (dst *MoveLocalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveLocalResponse.Merge(dst, src)
}
func (m *MoveLocalResponse) XXX_Size() int {
	return xxx_messageInfo_MoveLocalResponse.Size(m)
}
func (m *MoveLocalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveLocalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MoveLocalResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ListHostsRequest)(nil), "pb.ListHostsRequest")
	proto.RegisterType((*ListHostsResponse)(nil), "pb.ListHostsResponse")
	proto.RegisterType((*FileInfo)(nil), "pb.FileInfo")
	proto.RegisterType((*ListLocalDirRequest)(nil), "pb.ListLocalDirRequest")
	proto.RegisterType((*ListLocalDirResponse)(nil), "pb.ListLocalDirResponse")
	proto.RegisterType((*MkdirLocalRequest)(nil), "pb.MkdirLocalRequest")
	proto.RegisterType((*MkdirLocalResponse)(nil), "pb.MkdirLocalResponse")
	proto.RegisterType((*MoveLocalRequest)(nil), "pb.MoveLocalRequest")
	proto.RegisterType((*MoveLocalResponse)(nil), "pb.MoveLocalResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FeServiceClient is the client API for FeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FeServiceClient interface {
	ListHosts(ctx context.Context, in *ListHostsRequest, opts ...grpc.CallOption) (*ListHostsResponse, error)
	ListLocalDir(ctx context.Context, in *ListLocalDirRequest, opts ...grpc.CallOption) (*ListLocalDirResponse, error)
	MkdirLocal(ctx context.Context, in *MkdirLocalRequest, opts ...grpc.CallOption) (*MkdirLocalResponse, error)
	MoveLocal(ctx context.Context, in *MoveLocalRequest, opts ...grpc.CallOption) (*MoveLocalResponse, error)
}

type feServiceClient struct {
	cc *grpc.ClientConn
}

func NewFeServiceClient(cc *grpc.ClientConn) FeServiceClient {
	return &feServiceClient{cc}
}

func (c *feServiceClient) ListHosts(ctx context.Context, in *ListHostsRequest, opts ...grpc.CallOption) (*ListHostsResponse, error) {
	out := new(ListHostsResponse)
	err := c.cc.Invoke(ctx, "/pb.FeService/ListHosts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feServiceClient) ListLocalDir(ctx context.Context, in *ListLocalDirRequest, opts ...grpc.CallOption) (*ListLocalDirResponse, error) {
	out := new(ListLocalDirResponse)
	err := c.cc.Invoke(ctx, "/pb.FeService/ListLocalDir", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feServiceClient) MkdirLocal(ctx context.Context, in *MkdirLocalRequest, opts ...grpc.CallOption) (*MkdirLocalResponse, error) {
	out := new(MkdirLocalResponse)
	err := c.cc.Invoke(ctx, "/pb.FeService/MkdirLocal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feServiceClient) MoveLocal(ctx context.Context, in *MoveLocalRequest, opts ...grpc.CallOption) (*MoveLocalResponse, error) {
	out := new(MoveLocalResponse)
	err := c.cc.Invoke(ctx, "/pb.FeService/MoveLocal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FeServiceServer is the server API for FeService service.
type FeServiceServer interface {
	ListHosts(context.Context, *ListHostsRequest) (*ListHostsResponse, error)
	ListLocalDir(context.Context, *ListLocalDirRequest) (*ListLocalDirResponse, error)
	MkdirLocal(context.Context, *MkdirLocalRequest) (*MkdirLocalResponse, error)
	MoveLocal(context.Context, *MoveLocalRequest) (*MoveLocalResponse, error)
}

func RegisterFeServiceServer(s *grpc.Server, srv FeServiceServer) {
	s.RegisterService(&_FeService_serviceDesc, srv)
}

func _FeService_ListHosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeServiceServer).ListHosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.FeService/ListHosts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeServiceServer).ListHosts(ctx, req.(*ListHostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeService_ListLocalDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLocalDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeServiceServer).ListLocalDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.FeService/ListLocalDir",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeServiceServer).ListLocalDir(ctx, req.(*ListLocalDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeService_MkdirLocal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MkdirLocalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeServiceServer).MkdirLocal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.FeService/MkdirLocal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeServiceServer).MkdirLocal(ctx, req.(*MkdirLocalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeService_MoveLocal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveLocalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeServiceServer).MoveLocal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.FeService/MoveLocal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeServiceServer).MoveLocal(ctx, req.(*MoveLocalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.FeService",
	HandlerType: (*FeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListHosts",
			Handler:    _FeService_ListHosts_Handler,
		},
		{
			MethodName: "ListLocalDir",
			Handler:    _FeService_ListLocalDir_Handler,
		},
		{
			MethodName: "MkdirLocal",
			Handler:    _FeService_MkdirLocal_Handler,
		},
		{
			MethodName: "MoveLocal",
			Handler:    _FeService_MoveLocal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "otaru-fe.proto",
}

func init() { proto.RegisterFile("otaru-fe.proto", fileDescriptor_otaru_fe_dd9b886daca14798) }

var fileDescriptor_otaru_fe_dd9b886daca14798 = []byte{
	// 604 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0xcf, 0x6e, 0xd3, 0x4e,
	0x10, 0xd6, 0x26, 0xed, 0xef, 0x57, 0x6f, 0x93, 0x2a, 0xdd, 0xfe, 0xc1, 0xb8, 0xa8, 0x72, 0xcd,
	0x81, 0x10, 0x91, 0x98, 0x86, 0x5b, 0x4e, 0x14, 0xaa, 0x8a, 0xa0, 0x06, 0x90, 0xdb, 0x43, 0x4f,
	0x44, 0x8e, 0x3d, 0x71, 0xb6, 0xd8, 0xde, 0xc5, 0xbb, 0x09, 0x84, 0x1b, 0x48, 0xbc, 0x00, 0x1c,
	0x78, 0x30, 0x5e, 0x81, 0x97, 0xe0, 0x86, 0x76, 0xed, 0x94, 0x34, 0x96, 0x38, 0x65, 0xfd, 0xcd,
	0x37, 0xdf, 0xcc, 0x7c, 0x93, 0xc1, 0x5b, 0x4c, 0xfa, 0xd9, 0xb4, 0x3d, 0x86, 0x0e, 0xcf, 0x98,
	0x64, 0xa4, 0xc2, 0x47, 0xd6, 0xa6, 0xc6, 0x72, 0xc0, 0xba, 0x17, 0x31, 0x16, 0xc5, 0xe0, 0xfa,
	0x9c, 0xba, 0x7e, 0x9a, 0x32, 0xe9, 0x4b, 0xca, 0x52, 0x51, 0x44, 0x1f, 0xe9, 0x9f, 0xa0, 0x1d,
	0x41, 0xda, 0x16, 0x1f, 0xfc, 0x28, 0x82, 0xcc, 0x65, 0x5c, 0x33, 0xca, 0x6c, 0x87, 0xe0, 0xc6,
	0x39, 0x15, 0xf2, 0x05, 0x13, 0x52, 0x78, 0xf0, 0x7e, 0x0a, 0x42, 0x3a, 0x0f, 0xf0, 0xf6, 0x12,
	0x26, 0x38, 0x4b, 0x05, 0x10, 0x82, 0xd7, 0x26, 0x4c, 0x48, 0x13, 0xd9, 0xd5, 0xa6, 0xe1, 0xe9,
	0xb7, 0xf3, 0x03, 0xe1, 0x8d, 0x33, 0x1a, 0x43, 0x3f, 0x1d, 0x33, 0x45, 0x48, 0xfd, 0x04, 0x4c,
	0x64, 0x23, 0x45, 0x50, 0x6f, 0x72, 0x84, 0xd7, 0xe4, 0x9c, 0x83, 0x59, 0xb1, 0x51, 0x73, 0xab,
	0x5b, 0xef, 0xf0, 0x51, 0xa7, 0xff, 0x8a, 0x85, 0x70, 0x39, 0xe7, 0xe0, 0xe9, 0x90, 0x4a, 0x13,
	0xf4, 0x13, 0x98, 0x55, 0x1b, 0x35, 0xab, 0x9e, 0x7e, 0x93, 0x03, 0x6c, 0x70, 0xc8, 0x92, 0x61,
	0xc2, 0x42, 0x30, 0xd7, 0x6c, 0xd4, 0xac, 0x7b, 0x1b, 0x0a, 0x18, 0xb0, 0x10, 0xc8, 0x7d, 0x5c,
	0x4f, 0x58, 0x48, 0xc7, 0x14, 0xc2, 0xa1, 0xa4, 0x09, 0x98, 0xeb, 0x3a, 0xb3, 0xb6, 0x00, 0x2f,
	0x69, 0x02, 0xce, 0x43, 0xbc, 0xa3, 0x46, 0x38, 0x67, 0x81, 0x1f, 0x9f, 0xd2, 0xac, 0x98, 0x4c,
	0x15, 0xe3, 0xbe, 0x9c, 0x2c, 0x7a, 0x54, 0x6f, 0xa7, 0x87, 0x77, 0x6f, 0x53, 0x8b, 0x81, 0x1d,
	0xbc, 0x0e, 0xa9, 0xcc, 0xe6, 0x7a, 0xe2, 0xcd, 0x6e, 0x4d, 0x35, 0xbf, 0x18, 0xd6, 0xcb, 0x43,
	0xca, 0xa9, 0xc1, 0xbb, 0x90, 0x66, 0x3a, 0xf9, 0x5f, 0x45, 0x76, 0x31, 0x59, 0x26, 0xe6, 0x25,
	0x9c, 0x97, 0xb8, 0x31, 0x60, 0x33, 0xb8, 0x95, 0x7d, 0x17, 0x6f, 0xa8, 0x8c, 0xa1, 0xc8, 0x82,
	0x42, 0xe1, 0x7f, 0xf5, 0x7d, 0x91, 0x05, 0xda, 0x16, 0x15, 0x0a, 0x41, 0x48, 0x6d, 0xa9, 0xe1,
	0x69, 0xee, 0xa9, 0x5a, 0xda, 0x0e, 0xde, 0x5e, 0xd2, 0xca, 0x0b, 0x74, 0x7f, 0x57, 0xb0, 0x71,
	0x06, 0x17, 0x90, 0xcd, 0x68, 0x00, 0xc4, 0xc3, 0xc6, 0xcd, 0x5e, 0xc9, 0xae, 0x9a, 0x67, 0x75,
	0xf5, 0xd6, 0xde, 0x0a, 0x5a, 0x34, 0x6a, 0x7e, 0xf9, 0xf9, 0xeb, 0x7b, 0x85, 0x90, 0x86, 0xfe,
	0xcf, 0xcd, 0x8e, 0xdd, 0x31, 0xb8, 0x13, 0x2d, 0xf3, 0x16, 0xd7, 0x96, 0xdd, 0x23, 0x77, 0x16,
	0x02, 0x2b, 0xd6, 0x5b, 0x66, 0x39, 0x50, 0x88, 0x1f, 0x68, 0xf1, 0x3d, 0xb2, 0xb3, 0x24, 0x1e,
	0x2b, 0x92, 0x1b, 0x2b, 0x7d, 0xfc, 0xd7, 0x38, 0xa2, 0xdb, 0x2b, 0x39, 0x6e, 0xed, 0xaf, 0xc2,
	0x85, 0xf2, 0x91, 0x56, 0x3e, 0x70, 0xf6, 0x4b, 0xca, 0x89, 0x22, 0xf7, 0x50, 0x8b, 0x5c, 0x61,
	0xe3, 0xc6, 0xb6, 0xdc, 0x93, 0xd5, 0x8d, 0xe4, 0x9e, 0x94, 0xbc, 0x75, 0x0e, 0xb5, 0xb8, 0xe9,
	0x94, 0xdb, 0x4e, 0x66, 0x3d, 0xd4, 0x7a, 0xf6, 0x15, 0x7d, 0x3b, 0xf9, 0x8c, 0xc8, 0x15, 0xae,
	0xbd, 0x2e, 0xee, 0xd9, 0x3e, 0x79, 0xd3, 0x77, 0x9e, 0xe3, 0xba, 0xfe, 0xb6, 0x79, 0xc6, 0xae,
	0x21, 0x90, 0xe4, 0x70, 0x22, 0x25, 0x17, 0x3d, 0xd7, 0x8d, 0xa8, 0x9c, 0x4c, 0x47, 0x9d, 0x80,
	0x25, 0x6e, 0x3a, 0xf7, 0x3f, 0x4a, 0x57, 0xdf, 0xbc, 0x45, 0xa6, 0x90, 0xb2, 0xa7, 0x1a, 0x11,
	0x12, 0xb8, 0x8a, 0x77, 0xab, 0xc7, 0x9d, 0xc7, 0x2d, 0x54, 0xe9, 0x36, 0x7c, 0xce, 0x63, 0x1a,
	0xe8, 0x8b, 0x76, 0xaf, 0x05, 0x4b, 0x7b, 0x25, 0x64, 0xf4, 0x9f, 0x3e, 0xf4, 0x27, 0x7f, 0x02,
	0x00, 0x00, 0xff, 0xff, 0xbd, 0xf3, 0x1c, 0x0d, 0x57, 0x04, 0x00, 0x00,
}
