// Code generated by protoc-gen-go. DO NOT EDIT.
// source: otaru-fe.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
import pb "github.com/nyaxt/otaru/pb"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ListHostsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListHostsRequest) Reset()         { *m = ListHostsRequest{} }
func (m *ListHostsRequest) String() string { return proto.CompactTextString(m) }
func (*ListHostsRequest) ProtoMessage()    {}
func (*ListHostsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_otaru_fe_f34fab80bbc1be74, []int{0}
}
func (m *ListHostsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListHostsRequest.Unmarshal(m, b)
}
func (m *ListHostsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListHostsRequest.Marshal(b, m, deterministic)
}
func (dst *ListHostsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListHostsRequest.Merge(dst, src)
}
func (m *ListHostsRequest) XXX_Size() int {
	return xxx_messageInfo_ListHostsRequest.Size(m)
}
func (m *ListHostsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListHostsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListHostsRequest proto.InternalMessageInfo

type ListHostsResponse struct {
	Host                 []string `protobuf:"bytes,1,rep,name=host,proto3" json:"host,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListHostsResponse) Reset()         { *m = ListHostsResponse{} }
func (m *ListHostsResponse) String() string { return proto.CompactTextString(m) }
func (*ListHostsResponse) ProtoMessage()    {}
func (*ListHostsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_otaru_fe_f34fab80bbc1be74, []int{1}
}
func (m *ListHostsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListHostsResponse.Unmarshal(m, b)
}
func (m *ListHostsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListHostsResponse.Marshal(b, m, deterministic)
}
func (dst *ListHostsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListHostsResponse.Merge(dst, src)
}
func (m *ListHostsResponse) XXX_Size() int {
	return xxx_messageInfo_ListHostsResponse.Size(m)
}
func (m *ListHostsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListHostsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListHostsResponse proto.InternalMessageInfo

func (m *ListHostsResponse) GetHost() []string {
	if m != nil {
		return m.Host
	}
	return nil
}

type FileInfo struct {
	Name                 string       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 pb.INodeType `protobuf:"varint,2,opt,name=type,proto3,enum=pb.INodeType" json:"type,omitempty"`
	Size                 int64        `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	PermMode             uint32       `protobuf:"varint,4,opt,name=perm_mode,json=permMode,proto3" json:"perm_mode,omitempty"`
	ModifiedTime         int64        `protobuf:"varint,5,opt,name=modified_time,json=modifiedTime,proto3" json:"modified_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *FileInfo) Reset()         { *m = FileInfo{} }
func (m *FileInfo) String() string { return proto.CompactTextString(m) }
func (*FileInfo) ProtoMessage()    {}
func (*FileInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_otaru_fe_f34fab80bbc1be74, []int{2}
}
func (m *FileInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileInfo.Unmarshal(m, b)
}
func (m *FileInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileInfo.Marshal(b, m, deterministic)
}
func (dst *FileInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileInfo.Merge(dst, src)
}
func (m *FileInfo) XXX_Size() int {
	return xxx_messageInfo_FileInfo.Size(m)
}
func (m *FileInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FileInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FileInfo proto.InternalMessageInfo

func (m *FileInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FileInfo) GetType() pb.INodeType {
	if m != nil {
		return m.Type
	}
	return pb.INodeType_FILE
}

func (m *FileInfo) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *FileInfo) GetPermMode() uint32 {
	if m != nil {
		return m.PermMode
	}
	return 0
}

func (m *FileInfo) GetModifiedTime() int64 {
	if m != nil {
		return m.ModifiedTime
	}
	return 0
}

type ListLocalDirRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListLocalDirRequest) Reset()         { *m = ListLocalDirRequest{} }
func (m *ListLocalDirRequest) String() string { return proto.CompactTextString(m) }
func (*ListLocalDirRequest) ProtoMessage()    {}
func (*ListLocalDirRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_otaru_fe_f34fab80bbc1be74, []int{3}
}
func (m *ListLocalDirRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListLocalDirRequest.Unmarshal(m, b)
}
func (m *ListLocalDirRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListLocalDirRequest.Marshal(b, m, deterministic)
}
func (dst *ListLocalDirRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListLocalDirRequest.Merge(dst, src)
}
func (m *ListLocalDirRequest) XXX_Size() int {
	return xxx_messageInfo_ListLocalDirRequest.Size(m)
}
func (m *ListLocalDirRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListLocalDirRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListLocalDirRequest proto.InternalMessageInfo

func (m *ListLocalDirRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type ListLocalDirResponse struct {
	Entry                []*FileInfo `protobuf:"bytes,1,rep,name=entry,proto3" json:"entry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListLocalDirResponse) Reset()         { *m = ListLocalDirResponse{} }
func (m *ListLocalDirResponse) String() string { return proto.CompactTextString(m) }
func (*ListLocalDirResponse) ProtoMessage()    {}
func (*ListLocalDirResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_otaru_fe_f34fab80bbc1be74, []int{4}
}
func (m *ListLocalDirResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListLocalDirResponse.Unmarshal(m, b)
}
func (m *ListLocalDirResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListLocalDirResponse.Marshal(b, m, deterministic)
}
func (dst *ListLocalDirResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListLocalDirResponse.Merge(dst, src)
}
func (m *ListLocalDirResponse) XXX_Size() int {
	return xxx_messageInfo_ListLocalDirResponse.Size(m)
}
func (m *ListLocalDirResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListLocalDirResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListLocalDirResponse proto.InternalMessageInfo

func (m *ListLocalDirResponse) GetEntry() []*FileInfo {
	if m != nil {
		return m.Entry
	}
	return nil
}

type MoveLocalRequest struct {
	PathSrc              string   `protobuf:"bytes,1,opt,name=path_src,json=pathSrc,proto3" json:"path_src,omitempty"`
	PathDest             string   `protobuf:"bytes,2,opt,name=path_dest,json=pathDest,proto3" json:"path_dest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveLocalRequest) Reset()         { *m = MoveLocalRequest{} }
func (m *MoveLocalRequest) String() string { return proto.CompactTextString(m) }
func (*MoveLocalRequest) ProtoMessage()    {}
func (*MoveLocalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_otaru_fe_f34fab80bbc1be74, []int{5}
}
func (m *MoveLocalRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveLocalRequest.Unmarshal(m, b)
}
func (m *MoveLocalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveLocalRequest.Marshal(b, m, deterministic)
}
func (dst *MoveLocalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveLocalRequest.Merge(dst, src)
}
func (m *MoveLocalRequest) XXX_Size() int {
	return xxx_messageInfo_MoveLocalRequest.Size(m)
}
func (m *MoveLocalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveLocalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MoveLocalRequest proto.InternalMessageInfo

func (m *MoveLocalRequest) GetPathSrc() string {
	if m != nil {
		return m.PathSrc
	}
	return ""
}

func (m *MoveLocalRequest) GetPathDest() string {
	if m != nil {
		return m.PathDest
	}
	return ""
}

type MoveLocalResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveLocalResponse) Reset()         { *m = MoveLocalResponse{} }
func (m *MoveLocalResponse) String() string { return proto.CompactTextString(m) }
func (*MoveLocalResponse) ProtoMessage()    {}
func (*MoveLocalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_otaru_fe_f34fab80bbc1be74, []int{6}
}
func (m *MoveLocalResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveLocalResponse.Unmarshal(m, b)
}
func (m *MoveLocalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveLocalResponse.Marshal(b, m, deterministic)
}
func (dst *MoveLocalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveLocalResponse.Merge(dst, src)
}
func (m *MoveLocalResponse) XXX_Size() int {
	return xxx_messageInfo_MoveLocalResponse.Size(m)
}
func (m *MoveLocalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveLocalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MoveLocalResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ListHostsRequest)(nil), "pb.ListHostsRequest")
	proto.RegisterType((*ListHostsResponse)(nil), "pb.ListHostsResponse")
	proto.RegisterType((*FileInfo)(nil), "pb.FileInfo")
	proto.RegisterType((*ListLocalDirRequest)(nil), "pb.ListLocalDirRequest")
	proto.RegisterType((*ListLocalDirResponse)(nil), "pb.ListLocalDirResponse")
	proto.RegisterType((*MoveLocalRequest)(nil), "pb.MoveLocalRequest")
	proto.RegisterType((*MoveLocalResponse)(nil), "pb.MoveLocalResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FeServiceClient is the client API for FeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FeServiceClient interface {
	ListHosts(ctx context.Context, in *ListHostsRequest, opts ...grpc.CallOption) (*ListHostsResponse, error)
	ListLocalDir(ctx context.Context, in *ListLocalDirRequest, opts ...grpc.CallOption) (*ListLocalDirResponse, error)
	MoveLocal(ctx context.Context, in *MoveLocalRequest, opts ...grpc.CallOption) (*MoveLocalResponse, error)
}

type feServiceClient struct {
	cc *grpc.ClientConn
}

func NewFeServiceClient(cc *grpc.ClientConn) FeServiceClient {
	return &feServiceClient{cc}
}

func (c *feServiceClient) ListHosts(ctx context.Context, in *ListHostsRequest, opts ...grpc.CallOption) (*ListHostsResponse, error) {
	out := new(ListHostsResponse)
	err := c.cc.Invoke(ctx, "/pb.FeService/ListHosts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feServiceClient) ListLocalDir(ctx context.Context, in *ListLocalDirRequest, opts ...grpc.CallOption) (*ListLocalDirResponse, error) {
	out := new(ListLocalDirResponse)
	err := c.cc.Invoke(ctx, "/pb.FeService/ListLocalDir", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feServiceClient) MoveLocal(ctx context.Context, in *MoveLocalRequest, opts ...grpc.CallOption) (*MoveLocalResponse, error) {
	out := new(MoveLocalResponse)
	err := c.cc.Invoke(ctx, "/pb.FeService/MoveLocal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FeServiceServer is the server API for FeService service.
type FeServiceServer interface {
	ListHosts(context.Context, *ListHostsRequest) (*ListHostsResponse, error)
	ListLocalDir(context.Context, *ListLocalDirRequest) (*ListLocalDirResponse, error)
	MoveLocal(context.Context, *MoveLocalRequest) (*MoveLocalResponse, error)
}

func RegisterFeServiceServer(s *grpc.Server, srv FeServiceServer) {
	s.RegisterService(&_FeService_serviceDesc, srv)
}

func _FeService_ListHosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeServiceServer).ListHosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.FeService/ListHosts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeServiceServer).ListHosts(ctx, req.(*ListHostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeService_ListLocalDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLocalDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeServiceServer).ListLocalDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.FeService/ListLocalDir",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeServiceServer).ListLocalDir(ctx, req.(*ListLocalDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeService_MoveLocal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveLocalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeServiceServer).MoveLocal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.FeService/MoveLocal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeServiceServer).MoveLocal(ctx, req.(*MoveLocalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.FeService",
	HandlerType: (*FeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListHosts",
			Handler:    _FeService_ListHosts_Handler,
		},
		{
			MethodName: "ListLocalDir",
			Handler:    _FeService_ListLocalDir_Handler,
		},
		{
			MethodName: "MoveLocal",
			Handler:    _FeService_MoveLocal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "otaru-fe.proto",
}

func init() { proto.RegisterFile("otaru-fe.proto", fileDescriptor_otaru_fe_f34fab80bbc1be74) }

var fileDescriptor_otaru_fe_f34fab80bbc1be74 = []byte{
	// 558 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x53, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x95, 0x93, 0x16, 0xea, 0x6d, 0x52, 0xa5, 0x9b, 0x56, 0x98, 0x14, 0x55, 0xc6, 0x1c, 0x08,
	0x15, 0x89, 0x69, 0xb8, 0xe5, 0x44, 0xa1, 0xaa, 0x08, 0x6a, 0x01, 0xb9, 0x3d, 0xf4, 0x44, 0xe4,
	0xd8, 0x13, 0x67, 0x2b, 0x7b, 0x67, 0xf1, 0x6e, 0x02, 0xe1, 0x06, 0x12, 0x3f, 0x00, 0x07, 0xc4,
	0x77, 0xf1, 0x0b, 0x7c, 0x08, 0xda, 0xb5, 0x53, 0x85, 0xe4, 0xe4, 0xd9, 0x37, 0x6f, 0xdf, 0xcc,
	0x9b, 0xf5, 0x90, 0x1d, 0x54, 0x61, 0x3e, 0xed, 0x8c, 0xa1, 0x2b, 0x72, 0x54, 0x48, 0x2b, 0x62,
	0xd4, 0xda, 0x36, 0x58, 0x01, 0xb4, 0x1e, 0x24, 0x88, 0x49, 0x0a, 0x7e, 0x28, 0x98, 0x1f, 0x72,
	0x8e, 0x2a, 0x54, 0x0c, 0xb9, 0x2c, 0xb3, 0x4f, 0xcd, 0x27, 0xea, 0x24, 0xc0, 0x3b, 0xf2, 0x53,
	0x98, 0x24, 0x90, 0xfb, 0x28, 0x0c, 0x63, 0x9d, 0xed, 0x51, 0xd2, 0x38, 0x67, 0x52, 0xbd, 0x46,
	0xa9, 0x64, 0x00, 0x1f, 0xa7, 0x20, 0x95, 0xf7, 0x98, 0xec, 0x2e, 0x61, 0x52, 0x20, 0x97, 0x40,
	0x29, 0xd9, 0x98, 0xa0, 0x54, 0x8e, 0xe5, 0x56, 0xdb, 0x76, 0x60, 0x62, 0xef, 0x97, 0x45, 0xb6,
	0xce, 0x58, 0x0a, 0x03, 0x3e, 0x46, 0x4d, 0xe0, 0x61, 0x06, 0x8e, 0xe5, 0x5a, 0x9a, 0xa0, 0x63,
	0xfa, 0x90, 0x6c, 0xa8, 0xb9, 0x00, 0xa7, 0xe2, 0x5a, 0xed, 0x9d, 0x5e, 0xbd, 0x2b, 0x46, 0xdd,
	0xc1, 0x5b, 0x8c, 0xe1, 0x6a, 0x2e, 0x20, 0x30, 0x29, 0x7d, 0x4d, 0xb2, 0x2f, 0xe0, 0x54, 0x5d,
	0xab, 0x5d, 0x0d, 0x4c, 0x4c, 0x0f, 0x88, 0x2d, 0x20, 0xcf, 0x86, 0x19, 0xc6, 0xe0, 0x6c, 0xb8,
	0x56, 0xbb, 0x1e, 0x6c, 0x69, 0xe0, 0x02, 0x63, 0xa0, 0x8f, 0x48, 0x3d, 0xc3, 0x98, 0x8d, 0x19,
	0xc4, 0x43, 0xc5, 0x32, 0x70, 0x36, 0xcd, 0xcd, 0xda, 0x02, 0xbc, 0x62, 0x19, 0x78, 0x4f, 0x48,
	0x53, 0x5b, 0x38, 0xc7, 0x28, 0x4c, 0x4f, 0x59, 0x5e, 0x3a, 0xd3, 0xc5, 0x44, 0xa8, 0x26, 0x8b,
	0x1e, 0x75, 0xec, 0xf5, 0xc9, 0xde, 0xff, 0xd4, 0xd2, 0xb0, 0x47, 0x36, 0x81, 0xab, 0x7c, 0x6e,
	0x1c, 0x6f, 0xf7, 0x6a, 0xba, 0xf9, 0x85, 0xd9, 0xa0, 0x48, 0x79, 0x6f, 0x48, 0xe3, 0x02, 0x67,
	0x60, 0xee, 0x2e, 0x6a, 0xdc, 0x27, 0x5b, 0x5a, 0x77, 0x28, 0xf3, 0xa8, 0xac, 0x73, 0x57, 0x9f,
	0x2f, 0xf3, 0xc8, 0xf8, 0xd2, 0xa9, 0x18, 0xa4, 0x32, 0x33, 0xb1, 0x03, 0xc3, 0x3d, 0xd5, 0x53,
	0x6f, 0x92, 0xdd, 0x25, 0xad, 0xa2, 0x89, 0xde, 0xef, 0x0a, 0xb1, 0xcf, 0xe0, 0x12, 0xf2, 0x19,
	0x8b, 0x80, 0x06, 0xc4, 0xbe, 0x7d, 0x18, 0xba, 0xa7, 0x1b, 0x5a, 0x7d, 0xbb, 0xd6, 0xfe, 0x0a,
	0x5a, 0xe8, 0x78, 0xce, 0xb7, 0x3f, 0x7f, 0x7f, 0x56, 0x28, 0x6d, 0x98, 0x9f, 0x66, 0x76, 0xec,
	0x8f, 0xc1, 0x9f, 0x18, 0x99, 0x0f, 0xa4, 0xb6, 0x6c, 0x9f, 0xde, 0x5b, 0x08, 0xac, 0xcc, 0xae,
	0xe5, 0xac, 0x27, 0x4a, 0xf1, 0x03, 0x23, 0xbe, 0x4f, 0x9b, 0x4b, 0xe2, 0xa9, 0x26, 0xf9, 0xa9,
	0xa4, 0xd7, 0xc4, 0xbe, 0xb5, 0x55, 0xf4, 0xbc, 0x3a, 0xb1, 0xa2, 0xe7, 0x35, 0xef, 0xde, 0xa1,
	0x91, 0x75, 0xbc, 0x75, 0xd9, 0x6c, 0xd6, 0xb7, 0x8e, 0x5e, 0x7e, 0xb7, 0x7e, 0x9c, 0x7c, 0xb5,
	0xe8, 0x35, 0xa9, 0xbd, 0x2b, 0x17, 0xc6, 0x3d, 0x79, 0x3f, 0xf0, 0x5e, 0x91, 0xba, 0x39, 0xbb,
	0x22, 0xc7, 0x1b, 0x88, 0x14, 0x3d, 0x9c, 0x28, 0x25, 0x64, 0xdf, 0xf7, 0x13, 0xa6, 0x26, 0xd3,
	0x51, 0x37, 0xc2, 0xcc, 0xe7, 0xf3, 0xf0, 0xb3, 0xf2, 0xcd, 0x52, 0xb5, 0xe8, 0x14, 0x38, 0xbe,
	0x30, 0x88, 0x54, 0x20, 0x74, 0xbe, 0x57, 0x3d, 0xee, 0x3e, 0x3b, 0xb2, 0x2a, 0xbd, 0x46, 0x28,
	0x44, 0xca, 0x22, 0xb3, 0x32, 0xfe, 0x8d, 0x44, 0xde, 0x5f, 0x43, 0x46, 0x77, 0xcc, 0x26, 0x3d,
	0xff, 0x17, 0x00, 0x00, 0xff, 0xff, 0x34, 0xc6, 0x6e, 0x95, 0xb8, 0x03, 0x00, 0x00,
}
